
# @package task

_target_: dojo.config_dataclasses.task.agentssl.AgentSSLTaskConfig
benchmark: vtab
name: ???
setting: ???
shot: ???
seed: ???

# ~~~ Evaluation and results ~~~
submission_fname: submission.json