defaults:
  - /solver/client@debug.llm.client: litellm_4o

debug:
  _target_: dojo.config_dataclasses.operators.base.OperatorConfig
  llm:
    _target_: dojo.config_dataclasses.llm.generic_llm.GenericLLMConfig
    client: ???
    generation_kwargs: {}
  system_message_prompt_template:
    _target_: dojo.config_dataclasses.llm.jinjaprompt.JinjaPromptConfig
    template: |
      # Introduction:
      You are an expert in data-efficient machine learning and python programming who is tasked with
      fixing code bugs in a data-efficient machine learning program.
      Carefully review the previous debugging attempts, the buggy code and its terminal output in addition to the given task/data details, and available compute resources.
      You must not change the core idea or methodology of the solution, but only fix the bugs in the code.

      # Task Description:
      ````markdown
      {{task_desc}}
      ````

      {% if memory %}
      # Previous debugging attempts:
      ````markdown
      {{memory}}
      ````
      {% endif %}

      # Buggy Implementation:
      {{prev_buggy_code}}

      # Execution Output (Error):
      {{execution_output}}

      # Compute Environment:
      - Available Packages: {{packages}}
      - DO NOT DOWNLOAD NEW PACKAGES (You have access to pycocotools, torch, torchvision, ultralytics, etc.).

      # Instructions:
      - **Do NOT** alter the core method or underlying idea. Only correct existing bugs.
      - Outline your bug-fix plan clearly in 1-3 concise sentences.
      - Provide a single, complete Python code block wrapped in markdown (```python) that:
        - Implements the fix fully.
        - Is fully self-contained and executable as-is (The entire bug-free solution is given).

      - **Important Reminders:**
        - Absolutely do **NOT** skip any part of the code.
        - Make sure to print relevant training related information like the loss, accuracy, etc. 
        - Try to make the code run quickly and efficiently to get a quick proof of concept of your solution to the bug.

      Brainstorm about possible ways to fix the bug and WHY THEY ARE LIKELY TO FIX THE BUG for the given implementation. Additionally, if any other bugs further down the line are observed, please fix them as well.
      Generate a bug-fix plan that will structure and guide your step-by-step reasoning process. Reflect on it to make sure all the requirements are satisfied.

      Format the proposed bug-fix plan and code as follows:
      # Bug Fix Plan
      <bug-fix plan>
      
      ```python
      <the fixed python code>
      ```

    input_variables:
      - task_desc
      - prev_buggy_code
      - execution_output
      - execution_timeout
      - data_overview
      - memory
      - packages
