_target_: dojo.config_dataclasses.operators.memory.MemoryOpConfig
memory_processor: "plan_section_memory"
memory_op_kwargs:
  include_buggy_nodes: true
  section_headings:
    - "Idea to implement"
    - "Improvement Idea to implement"
    - "Tuning Idea to implement"
