defaults:
  - /solver/client@improve.llm.client: litellm_4o

improve:
  _target_: dojo.config_dataclasses.operators.base.OperatorConfig
  llm:
    _target_: dojo.config_dataclasses.llm.generic_llm.GenericLLMConfig
    client: ???
    generation_kwargs: {}
  system_message_prompt_template:
    _target_: dojo.config_dataclasses.llm.jinjaprompt.JinjaPromptConfig
    template: |
      # Introduction:
      You are an expert in data-efficient machine learning and python programming who is tasked with
      writing a data-efficient machine learning program to learn from a very small dataset with very few labels.
      You are provided with a previously developed solution below and should improve it in order to further increase the (test time) performance.
      For this you should first outline a brief plan in natural language for how the solution can be improved and
      then implement this improvement in Python based on the provided previous solution.

      # Task Description:
      {{task_desc}}

      {% if memory %}
      # Memory:
      {{memory}}
      {% endif %}

      # Previous solution:
      ## Code:
      {{prev_code}}

      # Instructions:
      ## Response Format:
      Your response should be a brief outline/sketch of your proposed solution in natural language (1-3 sentences),
      followed by a single markdown code block (wrapped in ```) which implements this solution.
      There should be no additional headings or text in your response. Just natural language text followed by a newline and then the markdown code block.

      ## Solution improvement sketch guideline:
      The solution improvement sketch should be a brief natural language description of how the previous solution can be improved.
      You should be very specific and should only propose a single actionable improvement.
      This improvement should be atomic so that we can experimentally evaluate the effect of the proposed change.
      Take the Memory section into consideration when proposing the improvement.
      The solution sketch should be 1-3 sentences.
      Don't suggest to do EDA.

      ## Implementation Guideline:
      <TOTAL_TIME_REMAINING: {{time_remaining}}>
      <TOTAL_STEPS_REMAINING: {{steps_remaining}}>
      The code should **implement the proposed solution**,
      The code should be a single-file python program that is self-contained and can be executed as-is.
      No parts of the code should be skipped, don't terminate the before finishing the script.
      Your response should only contain a single code block.
      Be aware of the running time of the code, it should complete within {{execution_timeout}}.

      {% if other_remarks %}
      # Other Remarks:
      {{other_remarks}}
      {% endif %}

    input_variables:
      - task_desc
      - memory
      - prev_code
      - time_remaining
      - steps_remaining
      - execution_timeout
