defaults:
  - greedy
  - /solver/operators/agentaps@operators:
    - aira_operators/debug
    - aira_operators/draft
    - aira_operators/improve
    - aide_operators/analyze
  - override memory: simple_memory
  - override memory@debug_memory: debug_memory
  - override memory@draft_memory: simple_memory_only_plans

improvement_steps: 5
data_preview: true

max_debug_depth: 5
debug_prob: 1.0

num_drafts: 5
max_llm_call_retries: 3
